# Generated by Django 2.1 on 2020-05-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200515_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('法学・政治学', 'law_politics'), ('医学・薬学', 'medical'), ('工学', 'engineering'), ('人文社会', 'social'), ('理学', 'science'), ('農学', 'agriculture'), ('経済学', 'economics'), ('教養', 'liberal_arts'), ('教育学', 'education')], default='', max_length=10, unique=True),
        ),
    ]
