# Generated by Django 2.1 on 2020-05-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200517_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='タイトルを入力してください', max_length=255, verbose_name='タイトルを記入してください'),
        ),
    ]
