# Generated by Django 2.1 on 2020-05-05 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followees',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
